# Chat event names
EVENT_GENERATION_RESTORE = "GENERATION_RESTORE"
EVENT_GENERATED_TEXT = "GENERATED_TEXT"
EVENT_MESSAGE_RESPONSE = "MESSAGE_RESPONSE"
EVENT_NEW_TOKEN = "NEW_TOKEN"
EVENT_END_GENERATION = "END_GENERATION"
EVENT_NEW_MESSAGE = "NEW_MESSAGE"


SUPPORT_REQUEST = 'SUPPORT_REQUEST'
SUPPORT_RESPONSE = 'SUPPORT_RESPONSE'
SUPPORT_MESSAGE = 'SUPPORT_MESSAGE'
END_SUPPORT_DIALOG_REQUEST = 'END_SUPPORT_DIALOG_REQUEST'
USER_FEEDBACK_REQUEST = 'USER_FEEDBACK_REQUEST'
USER_FEEDBACK_RESPONSE = 'USER_FEEDBACK_RESPONSE'
UPDATE_DIALOG_STATUS = 'UPDATE_DIALOG_STATUS'

# System event names
EVENT_PING = "PING"
EVENT_PONG = "PONG"

# Event statuses
STATUS_OK = "OK"