# Chat event names
EVENT_GENERATION_RESTORE = "GENERATION_RESTORE"
EVENT_GENERATED_TEXT = "GENERATED_TEXT"
EVENT_MESSAGE_RESPONSE = "MESSAGE_RESPONSE"
EVENT_NEW_TOKEN = "NEW_TOKEN"
EVENT_END_GENERATION = "END_GENERATION"
EVENT_NEW_MESSAGE = "NEW_MESSAGE"

# System event names
EVENT_PING = "PING"
EVENT_PONG = "PONG"

# Event statuses
STATUS_OK = "OK"